# Generated by Django 2.0.3 on 2018-04-01 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0006_album_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_from', models.CharField(max_length=250)),
                ('share_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
                ('share_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song')),
                ('share_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
