# Generated by Django 2.0.3 on 2018-04-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20180401_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='share_album',
        ),
        migrations.RemoveField(
            model_name='share',
            name='share_song',
        ),
        migrations.RemoveField(
            model_name='share',
            name='share_with',
        ),
        migrations.DeleteModel(
            name='Share',
        ),
    ]
